version: '2'

volumes:
  vastgoedfiles:

services:
  bedrijvenatlas:
    restart: always
    image: idgis/bedrijvenatlas:${BA_VERSION}
    ports:
      - "80:3000"
    environment:
      - REACT_APP_SETTINGS=${REACT_APP_SETTINGS}
    volumes:
      - vastgoedfiles:/usr/src/app/build/data

  funda-scraper:
    restart: always
    image: idgis/funda-scraper:${FUNDA_SCRAPER_VERSION}
    depends_on:
      - bedrijvenatlas
    environment:
      - GEMEENTE=${GEMEENTE}
      - BEDRIJVENTERREINEN_FEATURES=${BEDRIJVENTERREINEN_FEATURE_BOUNDS}
    volumes:
      - vastgoedfiles:/home/meteorapp/build/bundle/programs/web.browser/app/data
