version: '2'

volumes:
  vastgoedfiles:

services:
  bedrijvenatlas:
    restart: always
    image: idgis/bedrijvenatlas-${IMAGE_GEMEENTE}:${VERSION}
    ports:
      - "80:3000"
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
      - ROOT_URL=${ROOT_URL}
    volumes:
      - vastgoedfiles:/home/meteorapp/build/bundle/programs/web.browser/app/data

  funda-scraper:
    restart: always
    image: idgis/funda-scraper:1.1.1
    depends_on:
      - bedrijvenatlas
    environment:
      - GEMEENTE=${GEMEENTE}
    volumes:
      - vastgoedfiles:/home/meteorapp/build/bundle/programs/web.browser/app/data
